version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    depends_on:
      - ironman
    volumes:
      - ~/apps/ironman:/apps/ironman
      - ../config/nginx/prod:/etc/nginx/conf.d

  ironman:
    container_name: ironman
    image: musale/ironman:latest
    restart: always
    depends_on:
      - db
    volumes:
      - /var/log/ironman:/var/log/ironman
      - ~/apps/ironman:/apps/ironman
    env_file: ../.env

  db:
    container_name: db
    restart: always
    image: postgres:10.0
    volumes:
      - ironman_db:/var/lib/postgresql/data
    env_file: ../.env

volumes:
  ironman_db:
    driver: "local"
